//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\BDAGrammar.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class BDAGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, ATTRS=4, ID=5, SEP=6, OP=7;
	public const int
		RULE_query = 0;
	public static readonly string[] ruleNames = {
		"query"
	};

	private static readonly string[] _LiteralNames = {
		null, "'SELECT'", "'*'", "'FROM'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "ATTRS", "ID", "SEP", "OP"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BDAGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static BDAGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public BDAGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public BDAGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class QueryContext : ParserRuleContext {
		public ITerminalNode[] SEP() { return GetTokens(BDAGrammarParser.SEP); }
		public ITerminalNode SEP(int i) {
			return GetToken(BDAGrammarParser.SEP, i);
		}
		public ITerminalNode ID() { return GetToken(BDAGrammarParser.ID, 0); }
		public ITerminalNode OP() { return GetToken(BDAGrammarParser.OP, 0); }
		public ITerminalNode ATTRS() { return GetToken(BDAGrammarParser.ATTRS, 0); }
		public QueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_query; } }
		public override void EnterRule(IParseTreeListener listener) {
			IBDAGrammarListener typedListener = listener as IBDAGrammarListener;
			if (typedListener != null) typedListener.EnterQuery(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IBDAGrammarListener typedListener = listener as IBDAGrammarListener;
			if (typedListener != null) typedListener.ExitQuery(this);
		}
	}

	[RuleVersion(0)]
	public QueryContext query() {
		QueryContext _localctx = new QueryContext(Context, State);
		EnterRule(_localctx, 0, RULE_query);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 2; Match(T__0);
			State = 3; Match(SEP);
			State = 4;
			_la = TokenStream.LA(1);
			if ( !(_la==T__1 || _la==ATTRS) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 5; Match(SEP);
			State = 6; Match(T__2);
			State = 7; Match(SEP);
			State = 8; Match(ID);
			State = 9; Match(SEP);
			State = 10; Match(OP);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\t', '\xF', '\x4', '\x2', '\t', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x2', '\x2', '\x3', '\x4', '\x2', '\x4', '\x4', 
		'\x6', '\x6', '\x2', '\r', '\x2', '\x4', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'\x5', '\a', '\x3', '\x2', '\x2', '\x5', '\x6', '\a', '\b', '\x2', '\x2', 
		'\x6', '\a', '\t', '\x2', '\x2', '\x2', '\a', '\b', '\a', '\b', '\x2', 
		'\x2', '\b', '\t', '\a', '\x5', '\x2', '\x2', '\t', '\n', '\a', '\b', 
		'\x2', '\x2', '\n', '\v', '\a', '\a', '\x2', '\x2', '\v', '\f', '\a', 
		'\b', '\x2', '\x2', '\f', '\r', '\a', '\t', '\x2', '\x2', '\r', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
